// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRQxr9q1RjTwQJsTIqf8IS5XHZkQP3kU',
    appId: '1:630942576544:web:c7a50575b4fedccda03ec5',
    messagingSenderId: '630942576544',
    projectId: 'grupo-juvenil-morados',
    authDomain: 'grupo-juvenil-morados.firebaseapp.com',
    storageBucket: 'grupo-juvenil-morados.firebasestorage.app',
    measurementId: 'G-EJCDW6M8H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlObOG-AydDv6Bu8LGUvo_mcYIwYT4rg',
    appId: '1:630942576544:android:aeba264caa144b79a03ec5',
    messagingSenderId: '630942576544',
    projectId: 'grupo-juvenil-morados',
    storageBucket: 'grupo-juvenil-morados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjH3xfx9SrHqk7FbN2Vr1QXCRo-pCxHI',
    appId: '1:630942576544:ios:dec439779ce5be10a03ec5',
    messagingSenderId: '630942576544',
    projectId: 'grupo-juvenil-morados',
    storageBucket: 'grupo-juvenil-morados.firebasestorage.app',
    iosBundleId: 'com.example.grupoJuvenilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjH3xfx9SrHqk7FbN2Vr1QXCRo-pCxHI',
    appId: '1:630942576544:ios:dec439779ce5be10a03ec5',
    messagingSenderId: '630942576544',
    projectId: 'grupo-juvenil-morados',
    storageBucket: 'grupo-juvenil-morados.firebasestorage.app',
    iosBundleId: 'com.example.grupoJuvenilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRQxr9q1RjTwQJsTIqf8IS5XHZkQP3kU',
    appId: '1:630942576544:web:fafd8e9192bcd704a03ec5',
    messagingSenderId: '630942576544',
    projectId: 'grupo-juvenil-morados',
    authDomain: 'grupo-juvenil-morados.firebaseapp.com',
    storageBucket: 'grupo-juvenil-morados.firebasestorage.app',
    measurementId: 'G-DFPBPC2D9C',
  );
}
